fork_me_ribbon_url: https://github.com/coderefinery/git-intro
baseurl: "/git-intro"
title: "Git introduction"

source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']
exclude: ['LICENSE']

collections:
  episodes:
    output: true
    permalink: /:name/
  # guides are in a collection, otherwise site variables
  # like centralized_workflow_exercise_url are not understood
  guides:
    output: true
    permalink: /:name/
